# Lets only use sql-lite

import sqlite3


# By default, this creates a DB in disk, but can specify RAM if needed
conn = sqlite3.connect('chess.db')
c = conn.cursor()

# create tables
players_table = """ CREATE TABLE IF NOT EXISTS players (
                                    id integer PRIMARY KEY,
                                    name text NOT NULL,
                                    elo text
                                ); """
matches_table = """ CREATE TABLE IF NOT EXISTS matches (
                                    id integer PRIMARY KEY,
                                    player1_id integer NOT NULL, 
                                    player2_id integer NOT NULL,
                                    winning_player text NOT NULL,
                                    FOREIGN KEY(player1_id) REFERENCES players(id),
                                    FOREIGN KEY(player2_id) REFERENCES players(id)
                                ); """



match_details_table = """ CREATE TABLE IF NOT EXISTS match_details (
                                    id integer PRIMARY KEY,
                                    match_id integer NOT NULL,
                                    
                                    player1_move1 text,
                                    player2_move1 text,
                                    player1_move2 text,
                                    player2_move2 text,
                                    player1_move3 text,
                                    player2_move3 text,
                                    player1_move4 text,
                                    player2_move4 text,
                                    player1_move5 text,
                                    player2_move5 text,
                                    player1_move6 text,
                                    player2_move6 text,
                                    player1_move7 text,
                                    player2_move7 text,
                                    player1_move8 text,
                                    player2_move8 text,
                                    player1_move9 text,
                                    player2_move9 text,
                                    player1_move10 text,
                                    player2_move10 text,
                                    player1_move11 text,
                                    player2_move11 text,
                                    player1_move12 text,
                                    player2_move12 text,
                                    player1_move13 text,
                                    player2_move13 text,
                                    player1_move14 text,
                                    player2_move14 text,
                                    player1_move15 text,
                                    player2_move15 text,
                                    player1_move16 text,
                                    player2_move16 text,
                                    player1_move17 text,
                                    player2_move17 text,
                                    player1_move18 text,
                                    player2_move18 text,
                                    player1_move19 text,
                                    player2_move19 text,
                                    player1_move20 text,
                                    player2_move20 text,
                                    player1_move21 text,
                                    player2_move21 text,
                                    player1_move22 text,
                                    player2_move22 text,
                                    player1_move23 text,
                                    player2_move23 text,
                                    player1_move24 text,
                                    player2_move24 text,
                                    player1_move25 text,
                                    player2_move25 text,
                                    player1_move26 text,
                                    player2_move26 text,
                                    player1_move27 text,
                                    player2_move27 text,
                                    player1_move28 text,
                                    player2_move28 text,
                                    player1_move29 text,
                                    player2_move29 text,
                                    player1_move30 text,
                                    player2_move30 text,
                                    player1_move31 text,
                                    player2_move31 text,
                                    player1_move32 text,
                                    player2_move32 text,
                                    player1_move33 text,
                                    player2_move33 text,
                                    player1_move34 text,
                                    player2_move34 text,
                                    player1_move35 text,
                                    player2_move35 text,
                                    player1_move36 text,
                                    player2_move36 text,
                                    player1_move37 text,
                                    player2_move37 text,
                                    player1_move38 text,
                                    player2_move38 text,
                                    player1_move39 text,
                                    player2_move39 text,
                                    player1_move40 text,
                                    player2_move40 text,
                                    player1_move41 text,
                                    player2_move41 text,
                                    player1_move42 text,
                                    player2_move42 text,
                                    player1_move43 text,
                                    player2_move43 text,
                                    player1_move44 text,
                                    player2_move44 text,
                                    player1_move45 text,
                                    player2_move45 text,
                                    player1_move46 text,
                                    player2_move46 text,
                                    player1_move47 text,
                                    player2_move47 text,
                                    player1_move48 text,
                                    player2_move48 text,
                                    player1_move49 text,
                                    player2_move49 text,
                                    player1_move50 text,
                                    player2_move50 text,
                                    player1_move51 text,
                                    player2_move51 text,
                                    player1_move52 text,
                                    player2_move52 text,
                                    player1_move53 text,
                                    player2_move53 text,
                                    player1_move54 text,
                                    player2_move54 text,
                                    player1_move55 text,
                                    player2_move55 text,
                                    player1_move56 text,
                                    player2_move56 text,
                                    player1_move57 text,
                                    player2_move57 text,
                                    player1_move58 text,
                                    player2_move58 text,
                                    player1_move59 text,
                                    player2_move59 text,
                                    player1_move60 text,
                                    player2_move60 text,
                                    player1_move61 text,
                                    player2_move61 text,
                                    player1_move62 text,
                                    player2_move62 text,
                                    player1_move63 text,
                                    player2_move63 text,
                                    player1_move64 text,
                                    player2_move64 text,
                                    player1_move65 text,
                                    player2_move65 text,
                                    player1_move66 text,
                                    player2_move66 text,
                                    player1_move67 text,
                                    player2_move67 text,
                                    player1_move68 text,
                                    player2_move68 text,
                                    player1_move69 text,
                                    player2_move69 text,
                                    player1_move70 text,
                                    player2_move70 text,
                                    
                                    FOREIGN KEY (match_id) REFERENCES matches(id),
                                    FOREIGN KEY (player1_move1) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move1) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move2) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move2) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move3) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move3) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move4) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move4) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move5) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move5) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move6) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move6) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move7) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move7) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move8) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move8) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move9) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move9) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move10) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move10) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move11) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move11) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move12) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move12) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move13) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move13) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move14) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move14) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move15) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move15) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move16) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move16) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move17) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move17) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move18) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move18) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move19) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move19) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move20) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move20) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move21) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move21) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move22) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move22) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move23) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move23) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move24) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move24) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move25) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move25) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move26) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move26) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move27) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move27) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move28) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move28) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move29) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move29) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move30) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move30) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move31) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move31) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move32) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move32) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move33) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move33) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move34) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move34) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move35) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move35) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move36) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move36) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move37) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move37) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move38) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move38) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move39) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move39) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move40) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move40) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move41) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move41) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move42) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move42) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move43) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move43) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move44) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move44) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move45) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move45) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move46) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move46) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move47) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move47) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move48) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move48) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move49) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move49) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move50) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move50) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move51) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move51) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move52) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move52) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move53) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move53) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move54) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move54) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move55) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move55) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move56) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move56) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move57) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move57) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move58) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move58) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move59) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move59) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move60) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move60) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move61) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move61) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move62) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move62) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move63) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move63) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move64) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move64) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move65) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move65) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move66) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move66) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move67) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move67) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move68) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move68) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move69) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move69) REFERENCES moves_states(id),
                                    FOREIGN KEY (player1_move70) REFERENCES moves_states(id),
                                    FOREIGN KEY (player2_move70) REFERENCES moves_states(id)
                                ); """



moves_table = """ CREATE TABLE IF NOT EXISTS moves (
                                    id integer PRIMARY KEY,
                                    move text NOT NULL
                                ); """
states_table = """ CREATE TABLE IF NOT EXISTS states (
                                    id integer PRIMARY KEY,
                                    a1 text,
                                    a2 text,
                                    a3 text,
                                    a4 text,
                                    a6 text,
                                    a7 text,
                                    a8 text,
                                    b1 text,
                                    b2 text,
                                    b3 text,
                                    b4 text,
                                    b5 text,
                                    b6 text,
                                    b7 text,
                                    b8 text,
                                    c1 text,
                                    c2 text,
                                    c3 text,
                                    c4 text,
                                    c5 text,
                                    c6 text,
                                    c7 text,
                                    c8 text,
                                    d1 text,
                                    d2 text,
                                    d3 text,
                                    d4 text,
                                    d5 text,
                                    d6 text,
                                    d7 text,
                                    d8 text,
                                    e1 text,
                                    e2 text,
                                    e3 text,
                                    e4 text,
                                    e5 text,
                                    e6 text,
                                    e7 text,
                                    e8 text,
                                    f1 text,
                                    f2 text,
                                    f3 text,
                                    f4 text,
                                    f5 text,
                                    f6 text,
                                    f7 text,
                                    f8 text,
                                    g1 text,
                                    g2 text,
                                    g3 text,
                                    g4 text,
                                    g5 text,
                                    g6 text,
                                    g7 text,
                                    g8 text,
                                    h1 text,
                                    h2 text,
                                    h3 text,
                                    h4 text,
                                    h5 text,
                                    h6 text,
                                    h7 text,
                                    h8 text
                                ); """
moves_states_table = """ CREATE TABLE IF NOT EXISTS moves_states (
                                    id integer PRIMARY KEY,
                                    state1 integer NOT NULL,
                                    move_id integer NOT NULL,
                                    state2 integer NOT NULL,
                                    FOREIGN KEY (state1) REFERENCES states(id),
                                    FOREIGN KEY (move_id) REFERENCES moves(id),
                                    FOREIGN KEY (state2) REFERENCES states(id)
                                ); """

tables = [players_table, matches_table, match_details_table, moves_table, states_table, moves_states_table]
for table in tables:
    c.execute(table)

print("Local DB created for chess data")